/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Excepciones.lineaFacturaExistente;
import com.itextpdf.text.DocumentException;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Factura;
import modelo.LineaFactura;
import modelo.MetodoPago;
import modelo.Ordenador;
import modelo.Pieza;
import modelo.Producto;
import modelo.Servicio;

/**
 *
 * @author sportak
 */
public class generarFactura extends javax.swing.JFrame {

    /**
     * Creates new form generarFactura
     */
    private DefaultTableModel dtm;
    private DefaultTableModel dtm2;
    private ArrayList<LineaFactura> listaLineas = new ArrayList<>();

    public generarFactura() {
        initComponents();
        cargarComboClientes();
        this.buttonGroup1.add(this.radioOrdenadorProd);
        this.buttonGroup1.add(this.radioPiezaProd);
        this.buttonGroup1.add(this.radioServicioProd);
        this.buttonGroup2.add(this.radioEfectivo);
        this.buttonGroup2.add(this.radioVisa);
        this.buttonGroup2.add(this.radiobtn);
        this.buttonGroup2.add(this.radioeth);
        this.buttonGroup2.add(this.radioltc);
        this.buttonGroup2.add(this.radioiota);
        inicializarFactura();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboBoxCliente = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        radioOrdenadorProd = new javax.swing.JRadioButton();
        radioPiezaProd = new javax.swing.JRadioButton();
        radioServicioProd = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        eliminarLineaBtn = new javax.swing.JButton();
        añadirLineaBtn1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        radioEfectivo = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        radioVisa = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        radiobtn = new javax.swing.JRadioButton();
        radioeth = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        radioltc = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        radioiota = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        importeBruto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        descuentosTxt = new javax.swing.JTextField();
        ivaTxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtNeto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Elija un cliente:");

        comboBoxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxClienteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Elija un tipo de producto:");

        radioOrdenadorProd.setText("Ordenador");
        radioOrdenadorProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioOrdenadorProdActionPerformed(evt);
            }
        });

        radioPiezaProd.setText("Componentes");
        radioPiezaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPiezaProdActionPerformed(evt);
            }
        });

        radioServicioProd.setText("Servicios");
        radioServicioProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioServicioProdActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setText("Elija un producto cliqueando sobre el y luego pulse el boton +, para añadirlo en  la factura");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(radioOrdenadorProd)
                .addGap(18, 18, 18)
                .addComponent(radioPiezaProd)
                .addGap(18, 18, 18)
                .addComponent(radioServicioProd))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioServicioProd)
                    .addComponent(radioOrdenadorProd)
                    .addComponent(radioPiezaProd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );

        eliminarLineaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/substract.png"))); // NOI18N
        eliminarLineaBtn.setAlignmentY(0.0F);
        eliminarLineaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarLineaBtnActionPerformed(evt);
            }
        });

        añadirLineaBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add.png"))); // NOI18N
        añadirLineaBtn1.setAlignmentY(0.0F);
        añadirLineaBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirLineaBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane2.setViewportView(jTable2);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Factura preliminar:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Elija metodo de pago:");

        radioEfectivo.setText("Efectivo");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/eur@2x.png"))); // NOI18N

        radioVisa.setText("Tarjeta Bancaria");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/visa.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btc@2x.png"))); // NOI18N

        radiobtn.setText("Bitcoin");

        radioeth.setText("Ethereum");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/eth@2x.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ltc@2x.png"))); // NOI18N

        radioltc.setText("Litecoin");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/miota@2x.png"))); // NOI18N

        radioiota.setText("IOTA");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioEfectivo)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioVisa)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(radiobtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioeth)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioltc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioiota))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioEfectivo)
                    .addComponent(radioVisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radiobtn)
                    .addComponent(radioeth)
                    .addComponent(radioltc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(radioiota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel5.setText("Pagar en criptomonedas(btc,eth,ltc,IOTA) supone un descuento del 10% .");

        importeBruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importeBrutoActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Facturar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/receipt.png"))); // NOI18N

        jLabel14.setText("Importe Bruto");

        jLabel15.setText("DTO");

        jLabel16.setText("IVA");

        txtNeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNetoActionPerformed(evt);
            }
        });

        jLabel17.setText("Importe Neto");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Descuentos" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setToolTipText("");
        jScrollPane3.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(comboBoxCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(212, 212, 212))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eliminarLineaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(añadirLineaBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(importeBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addComponent(ivaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(descuentosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(txtNeto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(225, 225, 225))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(añadirLineaBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminarLineaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(importeBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(descuentosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15))
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ivaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(txtNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void añadirLineaBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirLineaBtn1ActionPerformed
        if (this.buttonGroup2.getSelection() != null) {
            LineaFactura lf;
            Producto p;
            int row = this.jTable1.getSelectedRow();
            String codigo = this.jTable1.getValueAt(row, 1).toString();
            p = controlador.GestionFicheros.listaTienda.get(0).buscarProducto(codigo);
            lf = new LineaFactura((int) Math.round(Math.random() * 1000), p, 1);
            listaLineas.add(lf);
            llenarTableFactura(listaLineas);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debes elegir un metodo de pago antes de agregar lineas!");
        }
    }//GEN-LAST:event_añadirLineaBtn1ActionPerformed

    private void eliminarLineaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarLineaBtnActionPerformed
        LineaFactura lf;
        Producto p;
        int row = this.jTable1.getSelectedRow();
        String codigo = this.jTable1.getValueAt(row, 1).toString();
        int i = 0;
        String resBusqueda;
        String[] arraySplit;
        while (i < dtm2.getRowCount()) {
            resBusqueda = dtm2.getValueAt(i, 1).toString();
            arraySplit = resBusqueda.split(" ");
            System.out.println(arraySplit[0]);
            if (arraySplit[0].trim().equalsIgnoreCase(codigo)) {
                System.out.println("detectado");
                dtm2.removeRow(i);
                break;
            }
            i++;
        }

    }//GEN-LAST:event_eliminarLineaBtnActionPerformed

    private void radioServicioProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioServicioProdActionPerformed
        if (this.radioServicioProd.isSelected()) {
            System.out.println("Elegiste servicio");
            dtm = new DefaultTableModel();
            this.jTable1.setModel(dtm);
            dtm.addColumn("Nombre");
            dtm.addColumn("Codigo");
            dtm.addColumn("Precio");
            dtm.addColumn("Horas de trabajo");
            this.llenarTablaServicio();
        }
    }//GEN-LAST:event_radioServicioProdActionPerformed

    private void radioPiezaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPiezaProdActionPerformed
        if (this.radioPiezaProd.isSelected()) {
            System.out.println("Elegiste pieza");
            dtm = new DefaultTableModel();
            this.jTable1.setModel(dtm);
            dtm.addColumn("Nombre");
            dtm.addColumn("Codigo");
            dtm.addColumn("Precio");
            dtm.addColumn("Unidades");
            this.llenarTablaPieza();
        }
    }//GEN-LAST:event_radioPiezaProdActionPerformed

    private void radioOrdenadorProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioOrdenadorProdActionPerformed
        if (this.radioOrdenadorProd.isSelected()) {
            System.out.println("Elegiste ordenador");
            dtm = new DefaultTableModel();
            this.jTable1.setModel(dtm);
            dtm.addColumn("Nombre");
            dtm.addColumn("Codigo");
            dtm.addColumn("Precio");
            dtm.addColumn("Cantidad de PCS");
            this.llenarTableOrdenador();

        }
    }//GEN-LAST:event_radioOrdenadorProdActionPerformed

    private void comboBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxClienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.buttonGroup2.getSelection() != null) {
            if (this.dtm2.getRowCount() > 0) {
                Cliente seleccionado = controlador.GestionFicheros.listaTienda.get(0).getListaClientes().get(this.comboBoxCliente.getSelectedIndex());
                Factura nuevaFactura = null;
                Factura facturaPdf = null;
                if (this.radioEfectivo.isSelected()) {
                    String impB = (this.importeBruto.getText().substring(0, this.importeBruto.getText().length() - 2)).replace(",", ".");
                    facturaPdf = new Factura(seleccionado, LocalDateTime.now().toString(), Double.parseDouble(impB.trim()), MetodoPago.EFECTIVO);
                    nuevaFactura = new Factura(seleccionado, LocalDateTime.now().toString(), Double.parseDouble(this.txtNeto.getText()), MetodoPago.EFECTIVO);
                }
                if (this.radioVisa.isSelected()) {
                    String impB = (this.importeBruto.getText().substring(0, this.importeBruto.getText().length() - 2)).replace(",", ".");
                    facturaPdf = new Factura(seleccionado, LocalDateTime.now().toString(), Double.parseDouble(impB.trim()), MetodoPago.TARJETA_BANCARIA);
                    nuevaFactura = new Factura(seleccionado, LocalDateTime.now().toString(), Double.parseDouble(this.txtNeto.getText()), MetodoPago.TARJETA_BANCARIA);
                }
                if (this.radiobtn.isSelected()) {
                    String impB = (this.importeBruto.getText().substring(0, this.importeBruto.getText().length() - 2)).replace(",", ".");
                    facturaPdf = new Factura(seleccionado, LocalDateTime.now().toString(), Double.parseDouble(impB.trim()), MetodoPago.BITCOIN);
                    nuevaFactura = new Factura(seleccionado, LocalDateTime.now().toString(), Double.parseDouble(this.txtNeto.getText()), MetodoPago.BITCOIN);
                }
                if (this.radioeth.isSelected()) {
                    String impB = (this.importeBruto.getText().substring(0, this.importeBruto.getText().length() - 2)).replace(",", ".");
                    facturaPdf = new Factura(seleccionado, LocalDateTime.now().toString(), Double.parseDouble(impB.trim()), MetodoPago.ETHEREUM);
                    nuevaFactura = new Factura(seleccionado, LocalDateTime.now().toString(), Double.parseDouble(this.txtNeto.getText()), MetodoPago.ETHEREUM);
                }
                if (this.radioltc.isSelected()) {
                    String impB = (this.importeBruto.getText().substring(0, this.importeBruto.getText().length() - 2)).replace(",", ".");
                    facturaPdf = new Factura(seleccionado, LocalDateTime.now().toString(), Double.parseDouble(impB.trim()), MetodoPago.LITECOIN);
                    nuevaFactura = new Factura(seleccionado, LocalDateTime.now().toString(), Double.parseDouble(this.txtNeto.getText()), MetodoPago.LITECOIN);
                }
                if (this.radioiota.isSelected()) {
                    String impB = (this.importeBruto.getText().substring(0, this.importeBruto.getText().length() - 2)).replace(",", ".");
                    facturaPdf = new Factura(seleccionado, LocalDateTime.now().toString(), Double.parseDouble(impB.trim()), MetodoPago.IOTA);
                    nuevaFactura = new Factura(seleccionado, LocalDateTime.now().toString(), Double.parseDouble(this.txtNeto.getText()), MetodoPago.IOTA);
                }
                for (int i = 0; i < this.listaLineas.size(); i++) {
                    nuevaFactura.añadirLineaAFacturaExpress(this.listaLineas.get(i));
                }
                while (this.dtm2.getRowCount() > 0) {
                    this.dtm2.removeRow(0);
                }
                this.listaLineas.removeAll(listaLineas);
                this.descuentosTxt.setText("");
                this.ivaTxt.setText("");
                this.importeBruto.setText("");
                this.txtNeto.setText("");
                try {
                    seleccionado.getFacturas().add(nuevaFactura);
                    controlador.GestionFicheros.altaFactura(nuevaFactura);
                    controlador.GestionFicheros.generarDocumentoFactura(nuevaFactura);

                    if (Desktop.isDesktopSupported()) {

                        File file = new File("tienda/facturas/PDF/" + nuevaFactura.getId() + "ConIMG.pdf");
                        Desktop.getDesktop().open(file);

                    }

                } catch (IOException ex) {
                    Logger.getLogger(generarFactura.class.getName()).log(Level.SEVERE, null, ex);
                } catch (DocumentException ex) {
                    Logger.getLogger(generarFactura.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(rootPane, "Factura con codigo " + nuevaFactura.getId() + " y numero de lineas " + nuevaFactura.getListaLineas().size() + " dada de alta exitosamente.");

            } else {
                JOptionPane.showMessageDialog(rootPane, "Debes introducir un producto minimo!");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debes elegir un metodo de pago");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void importeBrutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importeBrutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_importeBrutoActionPerformed

    private void txtNetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNetoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(generarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(generarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(generarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(generarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new generarFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadirLineaBtn1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> comboBoxCliente;
    private javax.swing.JTextField descuentosTxt;
    private javax.swing.JButton eliminarLineaBtn;
    private javax.swing.JTextField importeBruto;
    private javax.swing.JTextField ivaTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JRadioButton radioEfectivo;
    private javax.swing.JRadioButton radioOrdenadorProd;
    private javax.swing.JRadioButton radioPiezaProd;
    private javax.swing.JRadioButton radioServicioProd;
    private javax.swing.JRadioButton radioVisa;
    private javax.swing.JRadioButton radiobtn;
    private javax.swing.JRadioButton radioeth;
    private javax.swing.JRadioButton radioiota;
    private javax.swing.JRadioButton radioltc;
    private javax.swing.JTextField txtNeto;
    // End of variables declaration//GEN-END:variables
private void cargarComboClientes() {
        this.comboBoxCliente.removeAllItems();
        ArrayList<Cliente> listaClientes = controlador.GestionFicheros.getListaTienda().get(0).getListaClientes();
        for (int i = 0; i < listaClientes.size(); i++) {
            this.comboBoxCliente.addItem(listaClientes.get(i).getDni() + " : " + listaClientes.get(i).getNombre());
        }
    }

    private void llenarTablaServicio() {
        ArrayList<Producto> servicios = controlador.GestionFicheros.getListaTienda().get(0).getListaProductos();
        borrarTableServicio();
        for (int i = 0; i < servicios.size(); i++) {
            if (servicios.get(i) instanceof Servicio) {
                Servicio servicio = (Servicio) servicios.get(i);
                Object[] datos = {servicio.getNombre(), servicio.getCodigo(), servicio.getPrecio(), servicio.getTiempo()};
                dtm.addRow(datos);
                this.jTable1.setModel(dtm);
            }
        }
    }

    private void borrarTableServicio() {
        while (0 < dtm.getRowCount()) {
            dtm.removeRow(0);
        }
    }

    private void llenarTablaPieza() {
        ArrayList<Producto> piezas = controlador.GestionFicheros.getListaTienda().get(0).getListaProductos();
        borrarTablePieza();
        for (int i = 0; i < piezas.size(); i++) {
            if (piezas.get(i) instanceof Pieza) {
                Pieza pieza = (Pieza) piezas.get(i);
                Object[] datos = {pieza.getNombre(), pieza.getCodigo(), pieza.getPrecio(), pieza.getCantidad()};
                dtm.addRow(datos);
                this.jTable1.setModel(dtm);
            }
        }
    }

    private void borrarTablePieza() {
        while (0 < dtm.getRowCount()) {
            dtm.removeRow(0);
        }
    }

    private void llenarTableOrdenador() {
        ArrayList<Producto> ordenadores = controlador.GestionFicheros.getListaTienda().get(0).getListaProductos();
        borrarTableOrdenador();
        for (int i = 0; i < ordenadores.size(); i++) {
            if (ordenadores.get(i) instanceof Ordenador) {
                Ordenador ordenador = (Ordenador) ordenadores.get(i);
                Object[] datos = {ordenador.getNombre(), ordenador.getCodigo(), ordenador.getPrecio(), ordenador.getCantidad()};
                dtm.addRow(datos);
                this.jTable1.setModel(dtm);
            }
        }
    }

    private void borrarTableOrdenador() {
        while (0 < dtm.getRowCount()) {
            dtm.removeRow(0);
        }
    }

    private void inicializarFactura() {
        dtm2 = new DefaultTableModel();
        this.jTable2.setModel(dtm2);
        dtm2.addColumn("Codigo");
        dtm2.addColumn("Producto");
        this.jTable2.getColumnModel().getColumn(1).setPreferredWidth(75);
        dtm2.addColumn("Cantidad");
        dtm2.addColumn("Coste");
    }

    private void llenarTableFactura(ArrayList<LineaFactura> listalineas) {
        DecimalFormat df = new DecimalFormat("##.##");
        df.setRoundingMode(RoundingMode.DOWN);
        borrarTableFactura();
        float importe = 0;
        for (int i = 0; i < listalineas.size(); i++) {
            Object[] datos = {listalineas.get(i).getCodigoLinea(), listalineas.get(i).getProducto().toString(), listalineas.get(i).getCantidad(), listalineas.get(i).getCoste()};
            dtm2.addRow(datos);
            this.jTable2.setModel(dtm2);
            importe += listalineas.get(i).getCoste();
        }
        float res = importe;
        float descuento;
        float IVA;
        String neto = "";
        float calculoNeto = importe;
        this.importeBruto.setText(df.format(res) + " €");
        this.jList1.removeAll();
        DefaultListModel<String> model = new DefaultListModel<>();
        this.jList1.setModel(model);
        if (this.jTable2.getRowCount() > 10) {
            //Como ha solicitado mas de 10 unidades, le concedemos un descuento por volumen
            calculoNeto = (float) (calculoNeto * 0.98);
            model.addElement("Dto Volumen");
        }
        //aplicamos descuento por pronto pago
        calculoNeto = (float) (calculoNeto * 0.97);
        model.addElement("Dto PP");
        //Si va a pagar con criptomonedas....
        if (this.radiobtn.isSelected() || this.radioeth.isSelected() || this.radioiota.isSelected() || this.radioltc.isSelected()) {
            calculoNeto = (float) (calculoNeto * 0.90);
            model.addElement("Crypto DTO");
        }
        descuento = (importe - calculoNeto);
        //descuento = descuento.substring(0, 5);
        this.descuentosTxt.setText(df.format(descuento));
        IVA = (float) (calculoNeto * 0.21);
        //IVA = IVA.substring(0, 5);
        this.ivaTxt.setText(df.format(IVA));
        calculoNeto = (float) (calculoNeto * 1.21);
        neto += calculoNeto;
        this.txtNeto.setText(neto);

    }

    private void borrarTableFactura() {
        while (0 < dtm2.getRowCount()) {
            dtm2.removeRow(0);
        }
    }

}
